### ISSUE TITLE
What about a fake SMTP server support instead of email ?

### ISSUE THREAD

**Issue by minanagehsalalma** [darkarp/chromepass#25]
Just like this 
https://github.com/aydinnyunus/WifiPassword-Stealer

Also what do you think about these methods of protecting the excitable 
Here
https://github.com/hawksh/Hidden-miner-builder

**Comment by darkarp** [comment]
I will include that in the project Malkit. Chromepass has been discontinued in favor of Malkit. It has many more features but could work simply as Chromepass too.

**Comment by minanagehsalalma** [comment]
@darkarp thanks that would be great

Keep me updated.... what about the -email option in that tool ? does it require a password ?

**Comment by darkarp** [comment]
Well currently I believe it isn't working since the server I was on went down. However, when I bring it back up it won't need a password. In the future, I'll try to make it work with fake smtp however it is tricky to get it to work smoothly because depending on the email provider it could get flagged and not sent.

**Comment by darkarp** [comment]
When I have time I'll update it!

**Comment by minanagehsalalma** [comment]
> When I have time I'll update it!

Thanks
