### ISSUE TITLE
Doesn't work with whatsapp web

### ISSUE THREAD

**Issue by azsde** [darkarp/chromepass#30]
Retrieved cookies cannot be used to log in into my whatsapp web session using autocookie.

It works ok with facebook.

**Comment by darkarp** [comment]
It won't work with everything due to many reasons. Cookies may not be enough to authenticate everywhere. I'll look into whatsapp web, I'm not entirely sure how their authentication is done yet

**Comment by darkarp** [comment]
For WhatsApp web and other similar services, after further inspection, would require a complete simulation including the local storage data.  This kind of feature might come in the future but since it's quite a bit of a challenge due to very bad support for this, I will not be working on it at the moment.
